# Generated by Django 4.2.20 on 2025-04-12 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('communicationhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicetext',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voicetext',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_texts', to='users.user'),
        ),
    ]
