# Generated by Django 4.2.20 on 2025-04-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('communicationhub', '0004_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.AlterField(
            model_name='voicetext',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_texts', to='users.user'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
