# Generated by Django 4.2.20 on 2025-04-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('communicationhub', '0006_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('compliment', 'Compliment'), ('question', 'Question')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.user'),
        ),
    ]
