# Generated by Django 4.2.20 on 2025-04-12 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('location_status', models.CharField(choices=[('in_campus', 'In Campus'), ('out_campus', 'Out of Campus')], default='in_campus', max_length=20)),
                ('schedule_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('departed', 'Departed'), ('arrived', 'Arrived')], default='scheduled', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('stops', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tracker.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tracker.route')),
            ],
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], default='entry', max_length=5)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tracker.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=50)),
                ('assigned_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_tracker.bus')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(help_text='Scheduled arrival time')),
                ('actual_arrival_time', models.DateTimeField(blank=True, help_text='When the bus actually reached the stop', null=True)),
                ('stop_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('arrived', 'Arrived'), ('skipped', 'Skipped')], default='upcoming', help_text='Status of the stop (e.g. upcoming, arrived, skipped)', max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='bus_tracker.schedule', verbose_name='Related Schedule')),
            ],
            options={
                'ordering': ['arrival_time'],
                'indexes': [models.Index(fields=['arrival_time'], name='bus_tracker_arrival_0b20c0_idx')],
            },
        ),
    ]
