# Generated by Django 5.2 on 2025-04-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='email',
        ),
    ]
