# Generated by Django 5.2 on 2025-04-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocationhistory',
            name='status',
            field=models.CharField(choices=[('on_campus', 'On Campus'), ('scheduled', 'Scheduled'), ('departed', 'Departed')], default='On Campus', max_length=20),
        ),
    ]
