# Generated by Django 4.2.20 on 2025-04-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('warning', 'Warning'), ('security', 'Security'), ('critical', 'Critical'), ('clear', 'Clear')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('sender', models.CharField(max_length=255)),
            ],
        ),
    ]
