# Generated by Django 5.2 on 2025-04-10 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('VS', 'Visiting'), ('AJ', 'Adjunct')], default='FT', max_length=2)),
                ('department_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('is_active', models.BooleanField(default=True)),
                ('staff_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('joined_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
                'db_table': 'management',
                'ordering': ['-joined_date'],
            },
        ),
    ]
