# Generated by Django 5.2 on 2025-04-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='email',
            field=models.CharField(default='default@email.com', max_length=100),
        ),
    ]
