# Generated by Django 5.2 on 2025-04-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('STD', 'Student'), ('PAR', 'Parent'), ('VND', 'Vendor'), ('GST', 'Guest')], default='GST', max_length=3),
        ),
    ]
